# Dockerfile
FROM --platform=linux/x86_64 public.ecr.aws/docker/library/python:3.11

# 環境変数の設定
ENV PYTHONUNBUFFERED 1

# 作業ディレクトリの設定
WORKDIR /app

# 依存関係のインストール
#COPY ./django/requirements.txt /app/django
#RUN pip install --upgrade pip && \
#    pip install -r requirements.txt
