# Generated by Django 5.1 on 2024-08-31 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='ajust_app.event')),
            ],
            options={
                'unique_together': {('event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('O', '◯'), ('X', '✕'), ('D', '△')], max_length=1)),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ajust_app.eventdate')),
            ],
            options={
                'unique_together': {('name', 'event_date')},
            },
        ),
    ]
