# Generated by Django 5.1.1 on 2024-09-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajust_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ajust_app.event'),
        ),
        migrations.CreateModel(
            name='DateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_options', to='ajust_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1)),
                ('date_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ajust_app.dateoption')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ajust_app.participant')),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='date',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
